# Travis Configuration
#
# Travis runs the tests configured in tox.ini using tox-travis.  Tox is a
# automation tool for running tests in isolated virtual environments.
# https://github.com/tox-dev/tox-travis
#
# Code coverage reporting
# https://github.com/codecov/example-python

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install: pip install tox-travis codecov

script: tox

after_script:
  - pip install codecov
  - codecov
