# Travis Configuration
#
# Travis runs the tests configured in tox.ini using tox-travis.  Tox is a
# automation tool for running tests in isolated virtual environments.
# https://github.com/tox-dev/tox-travis
#
# Code coverage reporting
# https://github.com/codecov/example-python

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install: pip install --upgrade tox-travis codecov

script: tox

after_script:
  - pip install --upgrade codecov
  - codecov

branches:
  only:
  - master
  - develop
